<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('services',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('short_description')->nullable();$t->text('description')->nullable();$t->string('image')->nullable();$t->decimal('price_from',12,2)->nullable();$t->json('features')->nullable();$t->boolean('status')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('food_categories',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->boolean('status')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('foods',function(Blueprint $t){$t->id();$t->foreignId('category_id')->constrained('food_categories')->cascadeOnDelete();$t->string('name');$t->string('slug');$t->text('description')->nullable();$t->string('image')->nullable();$t->enum('diet_type',['veg','non_veg','mixed'])->default('veg');$t->decimal('price',12,2)->nullable();$t->boolean('is_jain')->default(false);$t->boolean('status')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();$t->index(['category_id','status']);});
 Schema::create('packages',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->decimal('price_per_person',12,2)->nullable();$t->unsignedInteger('min_guests')->nullable();$t->unsignedInteger('max_guests')->nullable();$t->string('image')->nullable();$t->json('features')->nullable();$t->text('terms')->nullable();$t->boolean('status')->default(true);$t->timestamps();});
 Schema::create('package_food',function(Blueprint $t){$t->id();$t->foreignId('package_id')->constrained()->cascadeOnDelete();$t->foreignId('food_id')->constrained('foods')->cascadeOnDelete();$t->unique(['package_id','food_id']);});
 Schema::create('additional_services',function(Blueprint $t){$t->id();$t->string('name');$t->text('description')->nullable();$t->decimal('price',12,2)->nullable();$t->boolean('status')->default(true);$t->timestamps();});
}};
